version: '3.9'

services:
  main:
    container_name: order-event-processor
    image: order-event-processor/main:1.0
    build:
      context: .
      dockerfile: ./OrderEventProcessor/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=postgres;Username=postgres;Password=postgres

  db:
    container_name: postgres-db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres-db: {}